version: '3.9'

services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:latest
    environment:
      - PUBLIC_DNS=domain
      - ORGANISATION_UNIT=unit
      - ORGANISATION=org
      - CITY=city
      - STATE=state
      - COUNTRY_CODE=country
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
