version: '3.9'

services:
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - proxy

  db:
    container_name: mariadb
    image: mariadb:latest
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  image-export:
    container_name: export
    image: jgraph/export-server:latest
    expose:
      - 8000
    networks:
      - nextcloud_network
    volumes:
      - ./fonts:/usr/share/fonts/drawio
    restart: unless-stopped

  drawio:
    container_name: drawio
    image: jgraph/drawio:latest
    environment:
      - VIRTUAL_HOST=drawio.YOUR-DOMAIN
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=drawio.YOUR-DOMAIN
      - LETSENCRYPT_EMAIL=YOUR-EMAIL
      - EXPORT_URL=http://image-export:8000/
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - image-export
    restart: unless-stopped

  app:
    container_name: nextcloud-app
    image: nextcloud:latest
    environment:
      - VIRTUAL_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_EMAIL=YOUR-EMAIL
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
